runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  secure: always
  static_files: shopify-angular-app/index.html
  upload: shopify-angular-app/index.html
- url: /
  secure: always
  static_dir: shopify-angular-app
- url: /.*
  secure: always
  redirect_http_response_code: 301
  static_files: shopify-angular-app/index.html
  upload: shopify-angular-app/index.html